"use client";
/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/8SRLpKX8Cke
 */
import {
  CardTitle,
  CardDescription,
  CardHeader,
  CardContent,
  CardFooter,
  Card,
} from "@/components/ui/card";
import { Label } from "@/components/ui/label";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import Link from "next/link";
import Image from "next/image";
import { signIn } from "next-auth/react";
import { useRouter } from "next/navigation";
import { Prisma } from "@prisma/client";

export default function Login() {
  const router = useRouter();
  const handleSubmit = async (event: React.FormEvent<HTMLFormElement>) =>  {
    event.preventDefault(); // デフォルトのフォーム送信を防ぐ

    const formData = new FormData(event.currentTarget);
    const username = formData.get("username");
    const password = formData.get("password");

    //prismaのログイン処理
    try {
      const res = await signIn("credentials", {
        redirect: true,
        username: username,
        password: password,
      }).then((res) => {
        router.push("/dashboard");
      });
    } catch (error) {
      console.log(error);
    }
    
  };
  return (
    <Card
      key="1"
      className="mx-auto mt-10 w-96 bg-white shadow-lg rounded-lg overflow-hidden"
    >
      <CardHeader className="p-6 flex items-center space-x-4">
        <DogIcon className="w-8 h-8" />
        <div className="text-center">
          <CardTitle className="text-2xl font-semibold text-gray-700">
            Login
          </CardTitle>
          <CardDescription className="text-gray-600 mt-2">
            Please enter your email and password
          </CardDescription>
        </div>
      </CardHeader>
      <form onSubmit={handleSubmit}>
        <CardContent className="p-6 space-y-4">
          <div className="space-y-2">
            <Label className="text-gray-700" htmlFor="username">
              Username
            </Label>
            <Input
              className="border border-gray-300 rounded w-full p-2"
              id="username"
              name="username"
              placeholder="m@example.com"
              required
              type="username"
            />
          </div>
          <div className="space-y-2">
            <Label className="text-gray-700" htmlFor="password">
              Password
            </Label>
            <Input
              className="border border-gray-300 rounded w-full p-2"
              id="password"
              name="password"
              required
              type="password"
            />
          </div>
        </CardContent>
        <CardFooter className="p-6 bg-gray-50 flex items-center justify-between">
          <Button
            className="bg-blue-500 text-white rounded px-4 py-2"
            type="submit"
          >
            Sign in
          </Button>
          <Link className="text-blue-500 hover:text-blue-600" href="/register">
            Forgot Password?
          </Link>
        </CardFooter>
      </form>
    </Card>
  );
}

function DogIcon(props) {
  return (
    <Image
      src="/オムそば丼キャラ切り抜き.png"
      width="100"
      height="100"
      {...props}
    />
  );
}
