"use client";
/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/8SRLpKX8Cke
 */
import {
  CardTitle,
  CardDescription,
  CardHeader,
  CardContent,
  CardFooter,
  Card,
} from "@/components/ui/card";
import { Label } from "@/components/ui/label";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import Link from "next/link";
import Image from "next/image";
import { useFormState } from "react-dom";
import React, { useEffect, useState } from 'react';
import { useRouter } from 'next/navigation';
import { authenticate } from "@/lib/actions";

export default function Login() {
  const [state, formAction] = useFormState(authenticate, undefined)
  const [shouldRedirect, setShouldRedirect] = useState(false);
  const router = useRouter();

  useEffect(() => {
    // フォーム送信が成功したかどうかをチェック
    if (state === 'success') {
      setShouldRedirect(true);
    }
  }, [state]);

  useEffect(() => {
    // リダイレクトを実行
    if (shouldRedirect) {
      const timer = setTimeout(() => {
        router.push('/dashboard'); // リダイレクト先のURLに変更
      }, 3000);

      return () => clearTimeout(timer);
    }
  }, [shouldRedirect, router]);

  return (
    <Card
      key="1"
      className="mx-auto mt-10 w-96 bg-white shadow-lg rounded-lg overflow-hidden"
    >
      <CardHeader className="p-6 flex items-center space-x-4">
        <DogIcon className="ml-4 w-16 h-16" />
        <div className="text-center">
          <CardTitle className="text-2xl font-semibold text-gray-700">
            ログイン
          </CardTitle>
          <CardDescription className="text-gray-600 mt-2">
            ユーザー名とパスワードを入力してください
          </CardDescription>
        </div>
      </CardHeader>
      <form action={formAction}>
        <CardContent className="p-6 space-y-4">
          <div className="space-y-2">
            <Label className="text-gray-700" htmlFor="username">
              ユーザー名
            </Label>
            <Input
              className="border border-gray-300 rounded w-full p-2"
              type="text"
              placeholder="username"
              name="username"
            />
          </div>
          <div className="space-y-2">
            <Label className="text-gray-700" htmlFor="password">
              パスワード
            </Label>
            <Input
              className="border border-gray-300 rounded w-full p-2"
              type="password"
              placeholder="password"
              name="password"
            />
          </div>
        </CardContent>
        <CardFooter className="p-6 bg-gray-50 flex items-center justify-between">
          <Button
            className="bg-blue-500 text-white rounded px-4 py-2"
            type="submit"
          >
            Sign in
          </Button>
          <Link className="text-blue-500 hover:text-blue-600" href="/register">
            Forgot Password?
          </Link>
        </CardFooter>
        {state && state}
      </form>
    </Card>
  );
}

function DogIcon(props) {
  return (
    <Image
      src="/オムそば丼キャラ切り抜き.png"
      width="100"
      height="100"
      {...props}
    />
  );
}
>>>>>>> Stashed changes
