/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/pLwboeks3JN
 */
import { CardTitle, CardDescription, CardHeader, CardContent, CardFooter, Card } from "@/components/ui/card"
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"
import Link from "next/link"

export function Register() {
  return (
    <Card key="1" className="mx-auto mt-10 w-96 bg-white shadow-lg rounded-lg overflow-hidden">
      <CardHeader className="p-6 flex items-center space-x-4">
        <DogIcon className="w-8 h-8" />
        <div className="text-center">
          <CardTitle className="text-2xl font-semibold text-gray-700">Register</CardTitle>
          <CardDescription className="text-gray-600 mt-2">Please fill in your details</CardDescription>
        </div>
      </CardHeader>
      <CardContent className="p-6 space-y-4">
        <div className="space-y-2">
          <Label className="text-gray-700" htmlFor="email">
            Email
          </Label>
          <Input
            className="border border-gray-300 rounded w-full p-2"
            id="email"
            placeholder="m@example.com"
            required
            type="email"
          />
        </div>
        <div className="space-y-2">
          <Label className="text-gray-700" htmlFor="password">
            Password
          </Label>
          <Input className="border border-gray-300 rounded w-full p-2" id="password" required type="password" />
        </div>
        <div className="space-y-2">
          <Label className="text-gray-700" htmlFor="confirmPassword">
            Confirm Password
          </Label>
          <Input className="border border-gray-300 rounded w-full p-2" id="confirmPassword" required type="password" />
        </div>
      </CardContent>
      <CardFooter className="p-6 bg-gray-50 flex items-center justify-between">
        <Button className="bg-blue-500 text-white rounded px-4 py-2" type="submit">
          Sign up
        </Button>
        <Link className="text-blue-500 hover:text-blue-600" href="#">
          Already have an account?
        </Link>
      </CardFooter>
    </Card>
  )
}


function DogIcon(props: React.SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M10 5.172C10 3.782 8.423 2.679 6.5 3c-2.823.47-4.113 6.006-4 7 .08.703 1.725 1.722 3.656 1 1.261-.472 1.96-1.45 2.344-2.5" />
      <path d="M14.267 5.172c0-1.39 1.577-2.493 3.5-2.172 2.823.47 4.113 6.006 4 7-.08.703-1.725 1.722-3.656 1-1.261-.472-1.855-1.45-2.239-2.5" />
      <path d="M8 14v.5" />
      <path d="M16 14v.5" />
      <path d="M11.25 16.25h1.5L12 17l-.75-.75Z" />
      <path d="M4.42 11.247A13.152 13.152 0 0 0 4 14.556C4 18.728 7.582 21 12 21s8-2.272 8-6.444c0-1.061-.162-2.2-.493-3.309m-9.243-6.082A8.801 8.801 0 0 1 12 5c.78 0 1.5.108 2.161.306" />
    </svg>
  )
}
